spring.application.name=RevaDo

# 1. Database Connection
# This will create a file named "revado.db" in your project root folder automatically.
spring.datasource.url=jdbc:sqlite:revado.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# 2. JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create-drop

# This tells Hibernate how to talk to SQLite specifically.
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# 3. Debugging (Optional)
# Set to true to see the raw SQL queries in your console (good for debugging).
spring.jpa.show-sql=true

#4 Springboot Actuator
management.endpoints.web.exposure.include=health

#5 Secret key used to sign and verify JWT tokens. private password that only your server knows
jwt.secret=VishrutiRevatureSecretKey@2026JWTRevadoProject!Secure123456

#6 Token expiration time in milliseconds (3600000 = 1 hour)
jwt.expiration-ms=3600000
